/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import java.math.BigDecimal;
import java.math.BigInteger;

public class App {

    private BigInteger e;
    private BigInteger p;
    private BigInteger q;
    private BigInteger n;
    private BigInteger k;

    public App(String pE,String pP,String pQ,String pN,String pKrip){
        e=new BigInteger(pE);
        p=new BigInteger(pP);
        q=new BigInteger(pQ);
        n=new BigInteger(pN);
        k=new BigInteger(pKrip);
    }

    public BigInteger getPrivateKey() {
        BigInteger one = new BigInteger("1");
        BigInteger phi = p.subtract(one).multiply( q.subtract(one));
        BigInteger d;
        d=e.modInverse(phi);
        return d;
    }

    public void deszifratu(){
        BigInteger pk=getPrivateKey();
        //k^d mod n
        BigInteger m=k.modPow(pk,n);
        System.out.println(m);
    }

    public static void main(String[] args) {
        new App("65537","317043256490461415472724153584731748683","322612182711011169170521985697248568707",
                "102282016990194715907376754685405290320613063451593543790128550772762982262881",
                "425415414914720205").deszifratu();
    }
}
